#!/usr/bin/env bash

readonly errorfile="/tmp/aaaa"

for _ in $(seq 1 2); do
    result=$(mysql -h"${MHA_MYSQL_SOURCE_HOST}" -P"${MHA_MYSQL_SOURCE_PORT}" -u"${MHA_MYSQL_SOURCE_USER}" -p"${MHA_MYSQL_SOURCE_PASS}" -N -se "SELECT 'ok';" 2>"$errorfile")
    if echo "$result" | grep -Eqw "^ok$"; then
        exit 0
    fi
    sleep $((RANDOM % 3))
done

if [[ -s "$errorfile" ]]; then
    grep -v 'Using a password on the command line interface can be insecure.' "$errorfile" >&2
    exit 1
fi
