name: Build Release

on:
  push:
    paths:
      - 'version'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version
        run: echo "VERSION=$(cat version)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mysql-ping:server-${{ env.VERSION }}
          platforms: linux/amd64

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.0.0

      - name: Compile client
        run: deno compile --allow-net mysqlping_client.ts -o mysqlping_client

      - name: Create Release and Upload binaries
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mysqlping_client
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
