name: Build Release

on:
  push:
    paths:
      - "version"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version
        run: echo "VERSION=$(cat version)" >> $GITHUB_ENV

      - name: Build the application
        run: |
          curl -fsSL https://bun.sh/install | bash -s "bun-v1.1.29"
          export BUN_INSTALL="$HOME/.bun"
          export PATH=$BUN_INSTALL/bin:$PATH
          bun add mysql2
          bun build --compile ./mysqlping_server.ts --minify --target=bun-linux-x64 --outfile mysqlping_server
          bun build --compile ./mysqlping_client.ts --minify --target=bun-linux-x64 --outfile mysqlping_client
          cp mysqlping_server mysqlping_server-${{ env.VERSION }}
          cp mysqlping_client mysqlping_client-${{ env.VERSION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mysql-ping:${{ env.VERSION }}
          platforms: linux/amd64

      - name: Create Release and Upload binaries
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mysqlping_server-${{ env.VERSION }}
            mysqlping_client-${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}